name: okx_demo
description: okx_demo
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  ffigen: ^9.0.1

# ffi 自动生成
ffigen:
  name: OkxSDK
  description: Bindings to `gen/headers/**.h`
  output:
    bindings: 'gen/ffigen_output/bindings.dart'
  headers:
    entry-points:
      - 'gen/headers/**.h'
  compiler-opts: '-I/opt/homebrew/opt/llvm/  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ -Wno-nullability-completeness'
